name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the Electron app
        run: npm run build

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.deb
          if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "version=$(jq -r .version package.json)"

      - name: Download MacOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact-macos-latest
          path: ./dist

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact-windows-latest
          path: ./dist

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact-ubuntu-latest
          path: ./dist

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.deb
          tag_name: v${{ env.version }}-${{ env.SHORT_SHA }}
          name: 'Release v${{ env.version }}-[${{ env.SHORT_SHA }}]'
          body: |
            This release was automatically generated by a GitHub Action.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
