name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-latest] # Build for Linux, Windows, and macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # Adjust this to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build # Adjust this to your build command

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ./dist/**  # Adjust this to your build output directory
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Remove unwanted files from release
        run: |
          echo "Cleaning up release artifacts..."
          for file in $(echo "${{ steps.create_release.outputs.upload_url }}" | grep -oP "[^ ]*\.yml|[^ ]*\.blockmap"); do
            echo "Removing $file"
            gh release delete "${{ github.ref_name }}" --force --yes "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
