name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Downgraded to ensure compatibility

      - name: Install dependencies
        run: npm install

      - name: Get version
        id: version
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Build the Electron app
        run: npm run build

      - name: Verify dist directory contents
        run: ls -l dist

      - name: Wait for files to be finalized
        run: sleep 10

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.deb
          if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ matrix.os }}
          path: ./dist

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*.{dmg,exe,deb}
          tag_name: v${{ env.version }}-${{ github.sha }}
          name: 'Release v${{ env.version }}-${{ github.sha }}'
          body: |
            This release was automatically generated by a GitHub Action.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
